### ISSUE TITLE
# 7 Part A Body mass index (BMI)

### ISSUE THREAD

**Issue by iamaliv3** [OER-Club/ProgrammingConcepts#11]
[Body mass index (BMI).docx](https://github.com/OER-Club/ProgrammingConcepts/files/6321654/Body.mass.index.BMI.docx)
[Body mass index (BMI).pdf](https://github.com/OER-Club/ProgrammingConcepts/files/6321655/Body.mass.index.BMI.pdf)

**Comment by eedom** [comment]
It looks good! i think it will be great if you add steps for the algorithm part

**Comment by OER-Club** [comment]
Show a stop to combine both print results.

**Comment by iamaliv3** [comment]
[Body mass index (BMI) .pdf](https://github.com/OER-Club/ProgrammingConcepts/files/6543177/Body.mass.index.BMI.pdf)
[Body mass index (BMI).docx](https://github.com/OER-Club/ProgrammingConcepts/files/6543178/Body.mass.index.BMI.docx)

Made suggested corrections.

**Comment by Jessica-Trujillo** [comment]
@iamaliv3 

It looked good. I went ahead and made a couple of convention changes, but I will go ahead and close this issue and mark it as being done on our document.

Thank you for the work well done!
