### ISSUE TITLE
Peer Review : Four-Digit integer summation

### ISSUE THREAD

**Issue by Jessica-Trujillo** [OER-Club/ProgrammingConcepts#3]
[FourDigit Summation.pdf](https://github.com/OER-Club/ProgrammingConcepts/files/6287965/FourDigit.Summation.pdf)

Please let me know if there are any correction you think I should make, or if the algorithm needs further explanation. 

Thank you
Jessica

**Comment by eedom** [comment]
Jessica it looks nice, well done!

**Comment by iamaliv3** [comment]
I think it looks good. Maybe add "if" and "else" on the arrows itself but other than that I don't see issues.

**Comment by OER-Club** [comment]
> I think it looks good. Maybe add "if" and "else" on the arrows itself but other than that I don't see issues.

I think in flow chart , we do not have to show if else.

**Comment by OER-Club** [comment]
> [FourDigit Summation.pdf](https://github.com/OER-Club/ProgrammingConcepts/files/6287965/FourDigit.Summation.pdf)
> 
> Please let me know if there are any correction you think I should make, or if the algorithm needs further explanation.
> 
> Thank you
> Jessica

Good work Thankyou and I think we can close this issue and move this file to completed.
