### ISSUE TITLE
Peer Review: Triangle Identification

### ISSUE THREAD

**Issue by Jessica-Trujillo** [OER-Club/ProgrammingConcepts#8]
Attached you will find the algorithm and flowchart for the Triangle Identification problem.

Please let me know if there are any changes that need to be made.

Thanks,
Jessica
[Triangle Identification.pdf](https://github.com/OER-Club/ProgrammingConcepts/files/6300303/Triangle.Identification.pdf)

**Comment by iamaliv3** [comment]
Looks good to me :) . Now I need to fix mine to look the same :).

**Comment by OER-Club** [comment]
All good , if the file is word doc , we can combine easily into one file, keep this and the word doc. Thanks

**Comment by Jessica-Trujillo** [comment]
> All good , if the file is word doc , we can combine easily into one file, keep this and the word doc. Thanks

Perfect I will go ahead and attach the word doc. and move forward with closing this issue
[Triangle Identification.docx](https://github.com/OER-Club/ProgrammingConcepts/files/6371165/Triangle.Identification.docx)
