### ISSUE TITLE
#5 Convert height in centimeters 

### ISSUE THREAD

**Issue by iamaliv3** [OER-Club/ProgrammingConcepts#9]
[Convert height in cm.docx](https://github.com/OER-Club/ProgrammingConcepts/files/6312310/Convert.height.in.cm.docx)
[Convert height in cm.pdf](https://github.com/OER-Club/ProgrammingConcepts/files/6312311/Convert.height.in.cm.pdf)

**Comment by eedom** [comment]
the all the flowchart should be blue  and the arrow colors green light should be all the same, see professor's sample on Teams, 
 
for the calculation part use flowchart- Data shape 
![image](https://user-images.githubusercontent.com/70550201/114897853-df4b2600-9dce-11eb-80a3-eb80fc8b1bd6.png)


Edom

**Comment by iamaliv3** [comment]
Oh, OK, Thank you. I will fix it.

**Comment by OER-Club** [comment]
1) Please use the same color format given in the sample.
2) Convert feet to inches and Convert inches to cm  Is that a decision to choose? If so give it in one single decision box and choice as output and then show how the calculation is done for conversions .

**Comment by iamaliv3** [comment]
[Convert height in cm.pdf](https://github.com/OER-Club/ProgrammingConcepts/files/6543104/Convert.height.in.cm.pdf)
[Convert height in cm.docx](https://github.com/OER-Club/ProgrammingConcepts/files/6543139/Convert.height.in.cm.docx)

 
Dr. Rajan, please check. Thank you.

**Comment by Jessica-Trujillo** [comment]
@iamaliv3 
This looks great! 
There were some minor things that needed changed, but nothing I couldn't take of really quick, this issue is being closed and marked as complete on document!

Thank you for the great work!
